# Generated by Django 5.2.10 on 2026-01-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('registration_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_tentative', models.BooleanField(default=False)),
                ('original_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='recruitment.recruitmentdrive')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
