# Generated by Django 5.2.10 on 2026-02-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruitmentapplication_assessment_score_and_more'),
        ('users', '0013_alter_memberprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='sig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.sig'),
        ),
        migrations.AddField(
            model_name='recruitmentassignment',
            name='submission_type',
            field=models.CharField(choices=[('FILE', 'File Upload'), ('LINK', 'Link Submission')], default='FILE', max_length=10),
        ),
    ]
