# Generated by Django 5.2.10 on 2026-02-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_recruitmentapplication_sig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('slot_duration', models.DurationField(blank=True, help_text='Duration of each interview slot', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='recruitment.recruitmentdrive')),
                ('members', models.ManyToManyField(blank=True, related_name='interview_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('drive', 'panel_number')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_slot', to='recruitment.recruitmentapplication')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='recruitment.interviewpanel')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
