# Generated by Django 5.2.10 on 2026-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_interviewpanel_interviewslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentdrive',
            name='candidate_name_field',
            field=models.CharField(blank=True, help_text='Field label for Candidate Name', max_length=200),
        ),
        migrations.AddField(
            model_name='recruitmentdrive',
            name='sig_field',
            field=models.CharField(blank=True, help_text='Field label for SIG/Interest', max_length=200),
        ),
    ]
