# Generated by Django 5.2.10 on 2026-01-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_due_date_event_is_full_event_event_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
    ]
